### PR TITLE
Parse the registration response in u2ftoken

### PR DESCRIPTION
**Pull request by awly**
Add a new u2ftoken.Token.RegisterParsed method which takes the raw
result of u2ftoken.Token.Register and parses it according to spec.

The format is described at:
https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-raw-message-formats-v1.2-ps-20170411.html#registration-response-message-success

Parsing the registration response is necessary to extract the key
handle for use in future authentication. It's also recommended to verify
the response signature and attestation certificate.

### CODE REVIEW

**Comment by awly** [comment]
note: I tested the example code against a Yubikey 5 nano

**Comment by daeMOn63** [comment]
Hey thanks, but looks like we already had this feature under the webauthn branch: https://github.com/flynn/u2f/blob/webauthn/u2ftoken/token.go#L147. We'll get it merged soon!

**Comment by awly** [comment]
Ah, didn't realize that branch touched the existing u2f code, great!
Looks like there was no activity on that branch for ~3 months. When do you think it'll merge?

**Comment by daeMOn63** [comment]
Yep we have been sidetracked a bit and left it there. Thanks a lot for having a look at it. I'll fix your comments and see about the merge. Can't promise on any ETA yet for the merge, there's a lot going on atm.

**Pull request closed without merging**
